version: '3.8'
services:
  app:
    build: .
    image: iamsroot/node-web-app_1.1
    ports:
      - '8081:8080'
    healthcheck:
      test: ["CMD-SHELL","curl --fail http://localhost:8081 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3
    restart: on-failure
    environment:
      - PORT=8081
    container_name: my-app4
    networks:
      - my-net

  app1:
    build: .
    image: iamsroot/node-web-app_1.1
    ports:
      - '8082:8080'
    healthcheck:
      test: ["CMD-SHELL","curl --fail http://localhost:8082 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3
    restart: on-failure
    environment:
      - PORT=8082
    container_name: my-app3
    networks:
      - my-net


networks:
  my-net:
    driver: bridge
    
    
    
