apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
    tier: frontend #tags
spec:
  replicas: 3 #number of replicas
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: iamsroot/node-web-app_1.1 #my docker image file
        ports:
        - containerPort: 3040 #internal port